dist: bionic
sudo: false

language: node_js
node_js:
  - "node"

cache: npm

install:
  - npm install
  - npm install -g nodemon
  

script:
<<<<<<< HEAD
  - npm start
=======
  - node server.js
>>>>>>> 5abc2b14e4be1dd69e54e25ece05b4c84bd292d5
